# Generated by Django 5.0.2 on 2024-04-22 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("client", "0002_alter_client_options"),
        ("products", "0002_alter_products_price_alter_products_quantity"),
        ("sellers", "0002_alter_positions_options_alter_sellers_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datatime", models.DateTimeField(verbose_name="Дата продажи")),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="client.client",
                        verbose_name="покупатель",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="products.products",
                        verbose_name="Товар",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sellers.sellers",
                        verbose_name="Продавец",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продажа",
                "verbose_name_plural": "Продажи",
            },
        ),
    ]
