# Generated by Django 5.0.2 on 2024-04-20 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Positions",
            fields=[
                (
                    "position",
                    models.CharField(
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Позиция в фирме",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sellers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=255, verbose_name="Фамилия")),
                ("phone", models.CharField(max_length=11, verbose_name="Телефон")),
                ("email", models.EmailField(max_length=255, verbose_name="E-mail")),
                ("data_in", models.DateField(verbose_name="Дата приема на работу")),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sellers.positions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
            },
        ),
    ]
