# Generated by Django 4.2.9 on 2024-03-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Название")),
                ("anons", models.CharField(max_length=250, verbose_name="Анонс")),
                ("full_text", models.TextField(verbose_name="Статья")),
            ],
        ),
    ]
