# Generated by Django 5.0.2 on 2024-03-28 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_feedback"),
    ]

    operations = [
        migrations.CreateModel(
            name="Countries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Название"
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="branch",
            name="title",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Заголовок"
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="country",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.countries",
            ),
        ),
    ]
