# Generated by Django 5.0.2 on 2024-04-01 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_countries_alter_branch_title_branch_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branch",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="country_branches",
                to="core.countries",
            ),
        ),
    ]
