# Generated by Django 4.2.9 on 2024-04-02 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_branch_country"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Название"
                    ),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="branch",
            options={"verbose_name": "Филиал", "verbose_name_plural": "Филиалы"},
        ),
        migrations.AddField(
            model_name="news",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="category_news",
                to="core.newscategory",
            ),
        ),
    ]
