# Generated by Django 4.2.9 on 2024-01-29 15:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Articles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="название")),
                ("anons", models.CharField(max_length=250, verbose_name="анонс")),
                ("full_text", models.TextField(verbose_name="статья")),
                ("date", models.DateTimeField(verbose_name="дата публикации")),
            ],
        ),
    ]
