# Generated by Django 5.0.2 on 2024-07-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[("waiting", "Waiting"), ("complete", "Complite")],
                default="waiting",
                max_length=20,
            ),
        ),
    ]
