# Generated by Django 5.0.6 on 2024-06-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lecture",
            name="stage",
            field=models.IntegerField(default=1),
        ),
    ]
