# Generated by Django 5.0.2 on 2024-04-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=255, verbose_name="Фамилия")),
                ("phone", models.CharField(max_length=11, verbose_name="Телефон")),
                ("email", models.EmailField(max_length=255, verbose_name="E-mail")),
            ],
        ),
    ]
