# Generated by Django 5.0.2 on 2024-04-17 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Имя")),
                ("text", models.CharField(max_length=255, verbose_name="Описание")),
                ("price", models.CharField(max_length=11, verbose_name="Стоимость")),
                (
                    "quantity",
                    models.EmailField(max_length=255, verbose_name="Количество"),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
            },
        ),
    ]
